### ISSUE TITLE
Failure during install: Too many levels of symbolic links

### ISSUE THREAD

**Issue by hackathi** [fkie-cad/common_helper_files#3]
This package breaks pipenv, a python environment manager.

Specifically, tests/data/recursive_broken_link causes a python `OSError` as pipenv walks through the directory during installation.

Can this artifact be removed from code? I understand that crashing python functions is the whole point of this file, however as you are using pytest anyways, is there any particular reason why this can't be dynamically initialised in a temporary directory using [pytest fixtures](https://docs.pytest.org/en/6.2.x/fixture.html#yield-fixtures-recommended)?

Re-creating the broken link doesn't seem too complicated to me.

**Comment by dorpvom** [comment]
Hi. We'll look into this. There should be an update rather soon. We generally know of the problem and have besides other things contributed to the python stdlib to handle this better.

**Comment by hackathi** [comment]
As a further note, pipenv itself is broken when installing this package; I have an open issue there as well: https://github.com/pypa/pipenv/issues/4763

The issues are however unrelated.

**Comment by jstucke** [comment]
#4 has removed the broken symlinks and added fixtures instead. It would be great if you could test it and check if it works with pipenv. If there are still problems, feel free to reopen the issue.

**Comment by hackathi** [comment]
After applying https://github.com/fkie-cad/common_helper_process/pull/3 to a fork of common_helper_process, it now installs and locks fine.

Thank you!
